### ISSUE TITLE
注册服务被kill掉, discovery依然存在

### ISSUE THREAD

**Issue by imsoul** [bilibili/discovery#68]
Linux使用kill -9把服务给kill掉, discovery没有监控到状态变化

[root@izwz9905avpr21bbhvlvuwz cmd]# nohup kratos run >log.log 2>&1 &
[1] 19614

kill -9 19614

**Comment by gitsrc** [comment]
Discovery's monitoring comes from two ways:
1. discovery-client actively sends offline signals
2. Discovery Discovery service healthy heartbeat period (default: 90s)
It is recommended that you do not use kill -9 to kill the process, because the Linux operating system restricts the process from being able to intercept the kill -9 signal. The client can intercept the kill signal and actively send offline signals to discovery.
